### PR TITLE
Configuration warning unrecognized property 'ssmToEnvironment'

### PR DESCRIPTION
**Pull request by invaderb**
Adding define function properties for ssmToEnvironment
Adding peer dependencies in package.json

### CODE REVIEW

**Comment by invaderb** [comment]
@gozup Here is the PR to fix the configuration warning/error in with the serverless.yaml

**Comment by invaderb** [comment]
@iblamefish @isbkch @mykolasmith @manulemoine

**Comment by gozup** [comment]
Thank you @invaderb 

I'm definitely going to merge this. However, I wanted to ask why did you add a peer dependency of serverless for version **2.55.0** since `defineFuntionEventProperties()` seems to have been introduced in version [2.11.0](https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2110-2020-11-06) ?

Thanks,
Emmanuel

**Comment by invaderb** [comment]
@gozup That's the the version I tested it on I can change it to version 2.11.0

The reason why I added the peer dependencies specifically was to follow the recommendation from serverless.
https://www.serverless.com/framework/docs/providers/aws/guide/plugins#writing-plugins

**Comment by gozup** [comment]
@invaderb yes, I'd recommend to set peerDependencies to:

```json
{
  "peerDependencies": {
    "serverless": "^2.11.0"
  }
}
```

**Comment by invaderb** [comment]
@gozup peer dependency corrected.

**Comment by invaderb** [comment]
@gozup Any update on merging this?

**Comment by gozup** [comment]
Hi @invaderb, 

Sorry for the delay. It's merged and deployed on NPM under version 1.1.0
https://www.npmjs.com/package/serverless-ssm-fetch

Best
Gozup

**Pull request merged**
