### PR TITLE
Do not store internal content on `serverless.variables` as it's scheduled to be removed

### PR DESCRIPTION
**Pull request by medikoo**
`serverless.variables` is scheduled to be removed with v3 of the Framework

### CODE REVIEW

**Comment by medikoo** [comment]
@gozup Is there a chance you can look into this PR? Without this, the plugin will not work with upcoming Serverless Framework v3 release

**Comment by gozup** [comment]
Hi @medikoo ,

Do you have any documented resource about it to share before I merge please?

Gozup

**Comment by medikoo** [comment]
@gozup https://www.serverless.com/framework/docs/deprecations#NEW_VARIABLES_RESOLVER

The `serlverless.variables` is an instance of old variables resolver that will no longer be in effect in v3 (note I'm the author of this change)

**Comment by gozup** [comment]
Hey @medikoo ,

I didn't merge your PR, but I've the modifications by myself since you edited the `dist` instead of the `src`. However, you're tagged as a contributor in the release: https://github.com/gozup/serverless-ssm-fetch/releases/tag/v1.1.2

Cheers!

**Comment by medikoo** [comment]
Thank you @gozup !

**Pull request closed without merging**
